### ISSUE TITLE
[meta] Implementação dos wireframes do besouro fase 1

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/besouro-app#1]
Issue meta pra organizar a implementação do front

**Comment by ricardopoppi** [comment]
@arkye @davidCarlos @danielhmarinho @laercios vamos já pensando como será a divisão de trabalho entre a Falcon e a Pencil na implementação das telas. Telas ligadas às missões ficam com a Pencil e telas ligadas às funcionalidades do EJ incluindo os cards de votação ficam com a Falcon?

Se tiverem uma proposta melhor a gente debate ela aqui nessa issue

**Comment by altjohndev** [comment]
Isso foi o que imaginei, mas precisarei de um _help_ para entender a estrutura que @davidCarlos e @danielhmarinho estão trabalhando no _front_.

**Comment by davidCarlos** [comment]
Eu ainda estou construindo a arquitetura do front usando polymer 3, tive que arrumar vários detalhes, uma vez que no SOMOS estamos usando polymer 2. Achei a decisão mais correta migrar logo para o polymer 3, uma vez que muita coisa com o polymer 2 não é retrocompativel. Eu já consegui fazer o servidor rodar, estou aplicando o básico do tema proposto pela design, e corrigindo alguns bugs que estão aparecendo. Começo da semana que vem eu já terei algo mais concreto pra apresentar. @arkye Podemos converçar na terça, e ai te mostro como está a arquitetura.

**Comment by ricardopoppi** [comment]
Fechando essa issue, pois agora estamos trabalhando a implementação e ajustes em issues específicas
