### ISSUE TITLE
Estilos do título e descrição da missão diferentes dos wireframes

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/besouro-app#12]
- [x] Nome autoria da missão
- [x] Espaçamento na descrição da missão
- [x] Indicadores no rodapé dos cards (img abaixo)

Versões wireframe:

![captura de tela de 2018-06-27 12-02-46](https://user-images.githubusercontent.com/1162183/41982658-5e98cbfe-7a02-11e8-966b-59bd93009592.png)

![captura de tela de 2018-06-27 12-26-16](https://user-images.githubusercontent.com/1162183/41983942-c6c27cd6-7a05-11e8-9970-d81c10b281c5.png)

Versões implementadas:

![whatsapp image 2018-06-27 at 03 37 44](https://user-images.githubusercontent.com/1162183/41982682-6aeec25a-7a02-11e8-9227-a1fc0b0346b4.jpeg)

![photo_2018-06-27_12-23-50](https://user-images.githubusercontent.com/1162183/41984017-f57948c0-7a05-11e8-8e21-e9440f79b005.jpg)

**Comment by ricardopoppi** [comment]
@luizapeixe peço analisar como as fontes propostas no design se comportaram no ambiente implementado. à primeira vista, parece que a leitura ficou um pouco embolada. alguma sugestão sobre isso?

**Comment by luizapeixe** [comment]
fiz um pequeno gabarito baseado no layout do sketch pra auxiliar nessa tarefa:

![captura de tela 2018-06-27 as 13 44 13](https://user-images.githubusercontent.com/6249788/41987675-3a04af02-7a10-11e8-8800-66231ec39710.png)


as partes assinaladas em rosa eu testei no próprio inspect do site e pareceu resolver bem a questão da diagramação dos textos
