### ISSUE TITLE
Formular proposta de splash de aceite de missão

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/besouro-app#13]
Atualmente estamos usando o padrão do somos, mas precisamos de um padrão besouro, incluindo a usabilidade de fechar o splash. Talvez um (x)?

O que está implementado hj:

![whatsapp image 2018-06-27 at 03 39 06](https://user-images.githubusercontent.com/1162183/41984173-6b929e30-7a06-11e8-9a0c-bd5d434c140f.jpeg)

**Comment by luizapeixe** [comment]
Segue uma primeira proposta aqui: https://invis.io/TMLZCTKW9F4#/305653432_Mobile_Portrait_Splash_Missa-o_Aceita

Sobre o recurso de fechar o splash, na proposta incluí um xzinho fora da caixa, mas a ideia é que o user tb feche a caixa se clicar fora dela e, além disso, ele volta à tela missão aceita no botão [ ver missão ]. Ainda sobre o recurso de fechar, talvez seja interessante a gente inclui-lo também nos splash de "[vc ganhou um troféu](https://invis.io/5VLZDWNA8PS#/305375052_Mobile_Portrait_Splash_De_Trofeu)" e "[opiniões da comunidade](https://invis.io/USLZDZH9MH3#/303446766_Mobile_Portrait_Frases)", que não é bem um splash mas tem uma visualidade similar. O que vcs acham?

**Comment by ricardopoppi** [comment]
Assim ficou bom, boa proposta. @luizapeixe dá uma olhada no protótipo do invision pra garantir que não há duas versões do splash. Se houver, move pra caídas. Bom trabalho!
