### ISSUE TITLE
Login por redes sociais não funcionam

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/besouro-app#15]
Clica no google e facebook e nada acontece

**Comment by altjohndev** [comment]
Requer criação dos endpoints para comunicação com a rede social, além da API. Será corrigido junto com o processo de refatoração da API do ej-server

**Comment by ricardopoppi** [comment]
@davidCarlos com a implementação do login social será importante avaliarmos se conseguimos, além do nome do usuário e email, importar algumas infos de localização também, entre outras
