### ISSUE TITLE
Foto de perfil quando tirada pela camera frontal é carregada invertida "deitada"

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/besouro-app#17]
Exemplos:

![whatsapp image 2018-06-27 at 03 45 14](https://user-images.githubusercontent.com/1162183/41984370-e279a142-7a06-11e8-8f89-87f6d0be7c2a.jpeg)
![photo_2018-06-27_12-36-52](https://user-images.githubusercontent.com/1162183/41984378-e5e9f78c-7a06-11e8-81ce-b7330020b541.jpg)

**Comment by davidCarlos** [comment]
Isso envolve perfil. Assinando a issue para o @arkye.

**Comment by ricardopoppi** [comment]
Fiz um novo debug, descobri que funciona bem quando a foto é tirada no modo paisagem. Um workaround pra esse bug poderia ser exibir algum aviso abaixo do botão pedindo pra tirar a foto com o celular deitado...será?

**Comment by danielhmarinho** [comment]
@ricardopoppi passei basicamente a tarde inteira pra entender o que estava acontecendo de fato. Celulares quando tiram fotos definem uma orientação própria pelo fato de que a câmera varia e a forma que as imagens são captadas também. Tendo isso em mente existem algumas formas de resolver esse problema, mas nenhuma é muito simples. Transformar em base64 e mudar os metadados. Ler o EXIF dela e partir das 8 posições possíveis definir um eixo de rotação. Existem libs próprias para resolver o problema também, mas não seria possível manter no nosso repositório. (https://github.com/blueimp/JavaScript-Load-Image)

Pensando dessa forma demoraria pelo menos uns 3 a 4 dias para implementar um comportamento parecido e deixar tudo estável, além de mudar a forma como recebemos a imagem da api.

Acho que seria a solução mais sensata ir pela linha que você pensou. Apenas avisar ao usuário que a foto deve ser colocada em paisagem. Os comportamentos de um pwa são diferentes de apps nativos e temos que tentar contornar esses problemas.

Se for algo com prioridade máxima podemos adequar no escopo desta segunda fase e ver a melhor solução.

**Comment by danielhmarinho** [comment]
![exif_orientations](https://user-images.githubusercontent.com/3606884/42786130-5f658bf2-892b-11e8-8da8-d03dd7ec56cb.jpg)
@ricardopoppi 
Isso explica melhor o problema que temos. O celular pode subir a foto em qualquer uma dessas posições, mas ele mesmo trata pro usuário na galeria ou aplicativos nativos, por isso temos esse problema no HTML

**Comment by ricardopoppi** [comment]
Que pesquisa sensacional Daniel. Mas realmente não é prioridade agora.

Vc pode incluir esse disclaimer abaixo do botão: "Se for tirar uma foto
nova, deite o celular" e fechar a issue. Bom que sua pesquisa fica
documentada aqui se formos atacar esse problema no futuro.
