### ISSUE TITLE
Conceber splash de boas vindas que aparece apenas no primeiro acesso

### ISSUE THREAD

**Issue by parrahenri** [unidoscontraacorrupcao/besouro-app#20]
Splash de boas vindas para contextualizar usuário:

"Que legal que você quer mobilizar o Brasil contra a corrupção!

Aqui você encontra diferentes missões de mobilização e pode se tornar ativista nessa campanha!"

**Comment by ricardopoppi** [comment]
A nossa proposta de wireframes tinha um paragrafo de boas vindas, vejam: https://projects.invisionapp.com/d/main#/console/14558908/302750832/preview#project_console

A questão é:
Opção 1) Colocar esse texto nesse paragrafo (que não foi implementado)
Opção 2) Manter sem esse primeiro parágrafo e transformar num splash

O que acham @parrahenri e @luizapeixe ?

**Comment by parrahenri** [comment]
Vamos tentar com o parágrafo primeiro! Pode resolver

**Comment by ricardopoppi** [comment]
Blz, vou fechar essa issue por enquanto então e colocar a implementação desse paragrafo no backlog da pencil
