### ISSUE TITLE
Implementar estilos no splash de ACEITE de missão

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/besouro-app#21]
Proposta de layout: https://github.com/unidoscontraacorrupcao/besouro-app/issues/13#issuecomment-400738348

Hoje está com o estilo padrão do somos:

![photo_2018-06-28_16-03-49](https://user-images.githubusercontent.com/1162183/42055226-e10fafae-7aec-11e8-99ee-24e8cb17e151.jpg)

**Comment by ricardopoppi** [comment]
@davidCarlos o texto pode seguir o padrão do wireframe, com esse texto do somos. Ficaria:

AGRADECEMOS SEU ENVOLVIMENTO!

Fique atento ao prazo restante e não deixe de concluir a missão

<botão ver missão>

**Comment by davidCarlos** [comment]
Acho que é bom dizer também, que a missão foi movida para a aba de "minhas missões", uma vez que ela some do inbox depois que é aceita. O que acham @ricardopoppi e @luizapeixe ?

**Comment by ricardopoppi** [comment]
De acordo. Vai ajudar o user a não se confundir. Nova versão:

AGRADECEMOS SEU ENVOLVIMENTO!

Fique atento ao prazo restante e não deixe de concluir a missão. Veja na aba "Minhas missões" essa e outras missões que você aceitou

<botão ver missão>
