### ISSUE TITLE
Integrar missões com conversations ativando o card "queremos ouvir sua opinião"

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/besouro-app#22]
Tarefas dessa issue, conforme planejamento da fase 2:

- [x] criar a relação missão x conversation: Durante a criação/edição de missões, o admin poderá associar uma ou mais conversations a uma missão. A relação não é exclusiva, uma conversation associada a uma missão permanecerá disponível para ser associada a outras missões

- [x] verificar se a API do EJ oferece os endpoints necessários

- [x] implementar os gatilhos: As conversations que forem associadas às missões serão usadas pela missão para disparar as frases aos usuários. Os gatilhos devem ser controlados globalmente. Toda vem que uma missão disparar as frases para o usuário deve pegar de uma conversa diferente associada a missão, no estilo round-robin, ou seja, em sequencia. O disparo das frases acontecerá em 4 momentos: 
    - [x] ~(i) no aceite da missão via splash de aceite, dando opção de "ver missão" ou "opinar" (o [splash de aceite](https://projects.invisionapp.com/d/main#/console/14558908/305653432/preview) precisa ser atualizado para essa opção, @luizapeixe ),~ 
    - [x] (ii) quando o usuário fizer o primeiro comentário dele na missão, aí o splash que aparece é [esse aqui](https://projects.invisionapp.com/share/AMKSPGK26WN#/screens/303446766_Mobile_Portrait_Frases), permitindo voto em 3 frases e no final mostrando o [splash de agradecimento](https://projects.invisionapp.com/share/AMKSPGK26WN#/screens/308482085_Mobile_Portrait_Frases_-_3) (sem pontuação agora na fase 2, então o texto de pontuação pode ser eliminado na implementação), oferecendo mais 3;
    - [x] (iii) quando o usuário clicar no enviar da conclusão da missão, por sequência de splashes idêntica ao caso acima (do primeiro comentário);
     - [x] (iv) quando o usuário receber uma notificação de frases para opinar. Clicando na notificação ele será levado ao show da missão, com a sequencia de splashes (a mesma do caso ii e iii) aparecendo pra ele

Atualizando aqui o corpo da issue com as especificações discutidas mais cedo com @davidCarlos:

(i) As frases são sempre exibidas em grupo de 3 frases aleatórias da mesma conversa;
(ii) Cada nova trinca de frase é puxada de uma nova conversa, da lista de conversas associada à missão;
(iii) Ao acabar a lista de conversas, o próximo gatilho retorna para a conversa inicial, percorrendo a lista de conversas novamente;
(iv) Uma conversa só deixa de ser exibida quando todas as suas frases tiverem sido votadas pelo usuário;
(v) Simplificar: se o usuário fechar o modal antes de votar nas 3 frases de uma conversa, o próximo gatilho pode pegar de uma nova conversa, mesmo que ele não tenha votado em 3 na anterior;
(vi) Se um usuário dispara o gatilho via push mas já votou em todas as frases de todas as conversas associadas a missão, é exibido pra ele [uma variação do splash de agradecimento](https://projects.invisionapp.com/share/2GN7UTNH8WS#/screens)

**Comment by luizapeixe** [comment]
a respeito do item (i) de implementar gatilhos, que tal a solução abaixo?

![captura de tela 2018-07-16 as 17 54 17](https://user-images.githubusercontent.com/6249788/42783156-6ce39f1c-8921-11e8-984f-763fcb1612aa.png)

Outra solução, dando mais prioridade às opiniões do que à página da missão, seria algo assim

![captura de tela 2018-07-16 as 18 01 47](https://user-images.githubusercontent.com/6249788/42783414-5a27e7ec-8922-11e8-842f-eeb89a6823a8.png)

No caso dessa segunda opção, o texto introdutório "Fixie tote bag (...)" precisaria explicar ao usuário o que é e o que faz o botão de "opinar".

E, sobre esse "opinar", estou em dúvida sobre as nomenclaturas de conversas/opiniões/votos. No momento o título do splash das opiniões é "queremos ouvir sua opinião" porém a ação é de VOTAR EM OPINIÕES e não exatamente FALAR AS OPINIÕES de fato. Então me pergunto se o botão não deveria ser algo como "votar em opiniões" ou algo parecido, ou se de fato estamos chamando de "OPINAR" a ação de "VOTAR EM OPINIÕES".

**Comment by ricardopoppi** [comment]
boas opções @luizapeixe fico em dúvida, mas me parece que é interessante dar mais preferencia pro ver missão mesmo, já que é o foco da ação de aceite, ainda que eu seja tentado a valorizar o opinar. mas acho que faz mais sentido pro usuário o ver missão na frente (cc @parrahenri )

sobre as nomenclaturas essa discussão vira e mexe volta no EJ. volta porque ainda testamos pouco em campo pra ter essa nitidez. vamos ter que escolher o que faz mais sentido pra aplicação do besouro. alguns pontos pra ajudar a gente a decidir:
1) as frases serão todas feitas pelo admin (pelo menos até fase 3 ou 4)
2) o ato de votar é a manifestação de uma opinião (concordo/discordo)
3) não faz sentido para o besouro a gente chamar de comentários, como no EJ

Nesse sentido, pode ainda fazer sentido as frases atuais, "ouvir sua opinião" e "opinar". O que acha @parrahenri ?

**Comment by parrahenri** [comment]
com certeza "opinião".

Curti, mas quando a pessoa aceita a missão eu não mostraria essa opção de somar pontos opinando. É uma distração que desvia do foco (a missão).

**Comment by ricardopoppi** [comment]
@parrahenri não mostrar aí significa abrir mão do gatilho do aceite. aí ficariam só 3 gatilhos: primeiro comentário, conclusão e via notificação. É por aí?

**Comment by parrahenri** [comment]
@luizapeixe e @ricardopoppi não dá pra botar esse gatilho na página da missão e não nessa intermediária pré-missão?

**Comment by ricardopoppi** [comment]
@parrahenri @luizapeixe no planning de fase 2 até fizemos um exercício de como poderia ser o gatilho de página de missão. Mas não chegamos numa proposta. Em que momento o usuário receberia as frases? Sempre que ele abrir a interna? Controles mais refinados implicariam em adiantar a inteligência de analytics do besouro, opção temerosa pra esse momento.

Alguma outra ideia vcs teriam?

**Comment by parrahenri** [comment]
Sim, tem que manter com baixa complexidade.
Minha proposta é que a frase convidando a opinar seja nessa tela: https://projects.invisionapp.com/d/main#/console/14558908/302750829/preview#project_console

Ou seja, depois que a pessoa concluiu a missão (cumpriu o fluxo da missão e agora pode ser convidada para um segundo fluxo)

Que acham?

**Comment by ricardopoppi** [comment]
Esse é o gatilho (ii), já previsto. Nesse momento eliminaríamos o gatilho (i) então, confere?

**Comment by parrahenri** [comment]
Eu acho, mas é o que vc comenta bem: não temos testes então é tudo chute agora... Se vocês dois acharem melhor manter eu não faço muita resistência tb. Tiraria pra deixar fluxos únicos por enquanto.

**Comment by ricardopoppi** [comment]
@davidCarlos atualizei o corpo da issue, riscando o primeiro gatilho

**Comment by ricardopoppi** [comment]
@davidCarlos com a formulação da regra das notificações de "frases para opinar" na issue #63 fiquei pensando que será necessário controlar o que exibir quando ele chega no show da missão com o splash de voto em frases já tendo votado anteriormente em todos os comentários de todas as conversas. Um usuário que já votou em tudo poderia clicar na notificação e aí não haveria frases para exibir. 

Talvez deva ser exibido uma variação do [splash de agradecimento](https://projects.invisionapp.com/share/AMKSPGK26WN#/screens/308482085_Mobile_Portrait_Frases_-_3) dizendo algo como "Obrigado! Você já votou em todas as opiniões dessa missão!". O que acha @luizapeixe ?

**Comment by luizapeixe** [comment]
concordo! sugiro algo tipo:

UAU!

VOCÊ VOTOU EM TODAS AS OPINIÕES DESSA MISSAO!

Daí um textinho extra tipo "Agradecemos demais seu engajamento! Sua contribuição é essencial para o projeto e lorem ipsum sit amet.." seria ideal um texto que continue estimulando a interação do user, via gameficação 

e o link "voltar" no fim do splash pra voltar à tela anterior

**Comment by ricardopoppi** [comment]
@luizapeixe achei massa. criei uma issue [ej-server#82](https://github.com/unidoscontraacorrupcao/ej-server/issues/82#issue-345009027) pra vc propor esse splash.

Sobre texto sugiro na mesma linha (cc @parrahenri):

UAU!
VOCÊ VOTOU EM TODAS AS OPINIÕES DESSA MISSAO!

Agradecemos demais seu engajamento! 
Aceite e conclua missões para ajudar ainda mais a campanha!

**Comment by ricardopoppi** [comment]
@davidCarlos atualizei no corpo da issue a variação do splash de agradecimento que aparece pro usuário que chega no modal de votação, via gatilho das notificações, mas porventura não tem mais frases pra votar (porque anteriormente já votou em todas): [variação do splash de agradecimento](https://projects.invisionapp.com/share/2GN7UTNH8WS#/screens)

**Comment by ricardopoppi** [comment]
fechando essa. a unica coisa que ficou faltando de integração com conversations é a https://github.com/unidoscontraacorrupcao/ej-server/issues/96
