### ISSUE TITLE
Definir regra de negócio para o card "opiniões da comunidade"

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/besouro-app#23]
@parrahenri precisamos definir qual a regra de negócio para a entrada do card. Exemplo:

(i) Entra um card assim que usuário aceita a missão, com voto em três frases seguidas?
(ii) Entra um card sempre que o usuário "visita" a página da missão, com voto em três frases seguidas?
(iii) Entra um card quando o usuário comenta numa missão pela primeira vez, com voto em três frases seguidas?

**Comment by parrahenri** [comment]
@ricardopoppi e @luizapeixe:

(i) Entra um card assim que usuário aceita a missão, com voto em três frases seguidas
Acho que essa não rola. Quando a pessoa aceita a missão, acho que o ideal é mandar ela pra alguma tela na qual ela executa a missão, não?

(ii) Entra um card sempre que o usuário "visita" a página da missão, com voto em três frases seguidas  e DANDO A POSSIBILIDADE DE OPINAR EM + 3 FRASES
boa!

(iii) Entra um card quando o usuário comenta numa missão pela primeira vez, com voto em três frases seguidas  e DANDO A POSSIBILIDADE DE OPINAR EM + 3 FRASES
Sim, logo DEPOIS que comentou. Que acham?

eu incluiria ainda:

(iv) Entra um card sempre que o usuário CONCLUI (comprova) uma missão, com voto em três frases seguidas e DANDO A POSSIBILIDADE DE OPINAR EM + 3 FRASES

Ficaria nesses 3 casos (sugeri excluir o primeiro) para testar

**Comment by ricardopoppi** [comment]
@parrahenri @luizapeixe além disso precisamos definir a regra de negócio para a entrada de novos comentários. creio que não temos tela de como o form de comentários seria exibido nesses casos

**Comment by parrahenri** [comment]
@ricardopoppi entrada de novos comentários em geral ou criados pelos participantes?

**Comment by ricardopoppi** [comment]
@parrahenri criados pelos participantes, ou seja, definir quando aparece a janela para novos comentários. Os comentários iniciais serão inseridos via admin

**Comment by parrahenri** [comment]
Massa! comentamos de isso ser um prêmio de acordo com conquistas anteriores (realizar missões, pontos ganhados votando em comentários). Ou seja, ideal é que apareça com essa narrativa de prêmio. 

Pode ser um troféu que fica preto e branco para as pessoas saberem que existe e lerem como podem ganhar ele.
Pode ser um splash que aparece quando os pré-requisitos forem atendidos

Que acham?

**Comment by ricardopoppi** [comment]
Eu acho ótimo. Hoje o mecanismo de gamificação só aceita troféu como pré-req. Acho que a melhor estratégia é pensar essas regras de negócio com base no que teremos na fase 3, ou seja, a interação dos usuários nos cards de candidatos. Daí podemos considerar como prereq:
(1) infos relativas à missões (missões concluidas, trofeus ganhos etc)
(2) infos relativas a votos nas frases
(3) infos relativas à interação nos candidatos

Em suma: minha proposta é criar isso pra fase 3 considerando o que teremos disponíveis até lá

**Comment by luizapeixe** [comment]
bacana pessoal! to aqui pensando como que o user pode ser notificado que ele ganhou o privilégio de criar comentário... Penso que se for só via um splash no momento de conquista do prêmio pode ser ruim porque o pressiona a cria-la naquele momento imediato. 

Acho que poderia funcionar melhor se ele recebesse uma NOTIFICAÇÃO, avisando da conquista do privilégio e indicando o link para página de criação do comentário. Assim ele usufruir do seu prêmio quando quiser (dentro da limitação do prêmio)

Dúvida: esse privilégio será limitado por quantidade de comentários ou por dias?

Outra dúvida: na tela de criação do comentário, o usuários será orientado a criar o comentário dentro de algum tema específico? Porque no EJ a própria conversa já indica o tema do comentário, né? Como será aqui no Besouro? Já temos ideia do conteúdo de texto dessa página?

**Comment by parrahenri** [comment]
Minha sugestão é que seja prêmio com diferentes níveis. Tipo um troféu que tenha nível 1, 2, 3, 4, 5, a cada XX pontos. Cada vez que o usuário ganha, tem direito a 1 comentário, sem prazo. Gosto da ideia de ser notificação @luizapeixe . 

Pensa notificação OU splash
ou
notificação E splash?

c/c: @ricardopoppi

**Comment by ricardopoppi** [comment]
@parrahenri @luizapeixe peço que planejem essa regra de negócio considerando não só os premios por missões mas também os de interação com os candidatos. Como ainda não formulamos o módulo de candidatos, essa issue tem que andar junto com a issue ej-server#39 que trata desse módulo

Em suma, nosso cronograma viável pra gamificação:
Fase 1: entrega dos primeiros trofeús com regras atreladas a missões
Fase 2: ajustes nesses troféus, ainda atrelados somente com missões
Fase 3: novas regras atreladas a interação com frases e candidatos, além de missões

**Comment by parrahenri** [comment]
Perfeito! O que falta prever ainda é a questão de troféus específicos e/ou pontos para a interação com candidatos né? Tentei resumir aqui:

----
----

MISSÕES
Cada missão da fase 1 equivale a XY pontos, além do troféu específico daquela missão.
 
OPINAR EM CARDS
(i) Entra um card sempre que o usuário "visita" a página da missão, com voto em três frases seguidas e DANDO A POSSIBILIDADE DE OPINAR EM + 3 FRASES
(ii) Entra um card DEPOIS que o usuário comenta numa missão pela primeira vez, com voto em três frases seguidas e DANDO A POSSIBILIDADE DE OPINAR EM + 3 FRASES
(iii) Entra um card sempre que o usuário CONCLUI (comprova) uma missão, com voto em três frases seguidas e DANDO A POSSIBILIDADE DE OPINAR EM + 3 FRASES
Cada opinião equivale a XZ pontos


COMENTAR

Prêmio com diferentes níveis. Tipo um troféu que tenha nível 1, 2, 3, 4, 5, a cada XX pontos. Cada vez que o usuário ganha, tem direito a 1 comentário, sem prazo.


INTERAGIR COM CANDIDATOS

Cada interação (LIKE/UNLIKE) equivale a XW pontos

se tivermos missões específicas na fase de candidaturas, elas entrarão da mesma forma como as missões da primeira fase, ou seja, renderão troféus específicos e pontos. Exemplo: Faça uma reunião com um candidato/a de sua cidade para apresentar as Novas Medidas e mande foto coprovando.

PONTUACAO GERAL

Mostrada no perfil e eventualmente em um ranking geral que possa ser filtrado por UF

**Comment by parrahenri** [comment]
@luizapeixe vou botar link da tela aqui, ok? https://invis.io/AMKSPGK26WN#/308482085_Mobile_Portrait_Frases_-_3

**Comment by parrahenri** [comment]
Hoje o texto é:

Opiniões da Comunidade
Parabéns!
Você acabou de ganhar XX pontos :D 
Continue votando e some ainda mais pontos de contribuições. 
vote em mais 3 opiniões

SUGESTÃO:

**Parabéns! (no lugar de opiniões de comunidade)
Você acabou de ganhar XX pontos :D 
Suas opiniões são muito importantes para identificar quais informações são de seu interesse, medir a importância que o combate à corrupção tem no Brasil e melhorar as estratégias da campanha!
vote em mais 3 opiniões**

**Comment by parrahenri** [comment]
Hoje o texto é:

Opiniões da comunidade 
Vote nas opiniões e some pontos de contribuição

SUGESTÃO

**Queremos ouvir sua opinião!
Vote e nos ajude a identificar ideias e ações importantes para melhorar a campanha.**

**Comment by parrahenri** [comment]
@luizapeixe e @ricardopoppi deixei sugestões dos conteúdos acima. Já os conteúdos da página de notificações (https://projects.invisionapp.com/share/AMKSPGK26WN#/screens/308496266) estão bons! Acho que só precisam mudar se cliente pedir ajustes! Parabéns por ir bem no alvo, luiza!

**Comment by luizapeixe** [comment]
atualizei os conteúdos das telas!
1: https://invis.io/AMKSPGK26WN#/303446766_Mobile_Portrait_Frases
2: https://invis.io/AMKSPGK26WN#/308482085_Mobile_Portrait_Frases_-_3

o papo de ontem ajudou bem na assertividade do processo :D valeu pessoal!

**Comment by ricardopoppi** [comment]
No planejamento da fase 2 não foi possível incluir a pontuação, pois exigiria aprimorar o componente de gamificação. Detalhei como será a implementação dos cards na fase 2 no corpo da issue de implementação a #22 (cc @parrahenri )

@luizapeixe observe que essa implementação requer um ajuste no splash de aceite da missão, expliquei tudo lá no [corpo da issue](https://github.com/unidoscontraacorrupcao/besouro-app/issues/22#issue-336743891)
