### ISSUE TITLE
Fazer proposta de interna de missão com título longo

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/besouro-app#24]
Hoje o limite do título da missão é de 100 caracteres. O layout atual previu apenas titulo curto.

Na implementação, conforme imagens abaixo, o titulo aparece encurtado, perdendo a leitura da "chamada da missão". @luizapeixe pode criar uma proposta de como um título de 100 caracteres seria exibido nesse caso.

![photo_2018-06-28_17-28-03](https://user-images.githubusercontent.com/1162183/42060591-bb5d4684-7afd-11e8-98ab-093415308e9e.jpg)
![photo_2018-06-28_17-28-02](https://user-images.githubusercontent.com/1162183/42060592-bb987222-7afd-11e8-84e4-74e9e5bbb12a.jpg)

**Comment by luizapeixe** [comment]
Para mantermos o estilo aplicado até o momento e mantendo o limite de 100 caracteres para os títulos das missões, ficamos com o layout assim:

![captura de tela 2018-07-02 as 14 24 06](https://user-images.githubusercontent.com/6249788/42177612-b656661c-7e03-11e8-8558-3924033ca094.png)

Se pudermos diminuir o limite para 80 caractéres, ficamos assim:

![captura de tela 2018-07-02 as 14 25 49](https://user-images.githubusercontent.com/6249788/42177684-002808f4-7e04-11e8-8fc4-d79df53490d9.png)

Outra solução seria diminuir o corpo do título

**Comment by ricardopoppi** [comment]
A solução ideal é a do limite em 80, pq mudar estilos agora pode ser traumático. Peço ao @davidCarlos que tá codando esse frente, opinar aqui também
