### ISSUE TITLE
Fazer proposta visual do que aparece na home quando ela estiver vazia (sem missões)

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/besouro-app#25]
Quando o usuário aceita todas as missões, a home fica vazia (img abaixo). @luizapeixe pode fazer uma proposta do que exibiremos para esse usuário?

![photo_2018-06-28_17-28-00](https://user-images.githubusercontent.com/1162183/42060844-94443110-7afe-11e8-98a2-3d85868a5e7b.jpg)

**Comment by luizapeixe** [comment]
que tal essa proposta, pessoal?

no invision -> https://invis.io/U5MBSL5AC2J#/306492382_Mobile_Portrait_Home_0_Missoes

**Comment by ricardopoppi** [comment]
Peço ao @parrahenri opinar sobre o conteúdo da msg. Também será necessário @luizapeixe uma versão pra quando a home de missões públicas estiver vazia (no caso em que o usuário tiver aceitado todas as disponíveis)

**Comment by parrahenri** [comment]
VOCÊ NÃO SE ENGAJOU EM NENHUMA MISSÃO AINDA

Vá às Missões Públicas e Aceite Alguma para Participar Conosco!

@luizapeixe sugestão de novo texto.

**Comment by parrahenri** [comment]
Sobre o texto mais longo de boas vindas, @ricardopoppi crio tb?

**Comment by luizapeixe** [comment]
@ricardopoppi , eu imaginei que as missões aceitas pelos users continuariam aparecendo na timeline das missões públicas, porém com o botão de ação alterado, ou seja, se o user já aceitou alguma missão disposta nas missões missões públicas, o botão no card da missão seria "Concluir missão" ou "Missão concluída". E missões expiradas poderiam aparecer somente na tl das missões pessoais mesmo. Faz sentido isso? se não, crio alguma solução por aqui para tela com feed público vazio

**Comment by parrahenri** [comment]
gosto dessa sugestão

**Comment by ricardopoppi** [comment]
humm acho que é por ai sim. tomamos uma decisão no desenvolvimento de tirar da feed publica, mas vamos pela sua concepção inicial sim. vou criar uma issue pra corrigir esse comportamento do app e outra pra implementar essa proposta do que aparecer qdo minhas missões estiver vazio.

com isso, fecho essa issue
