### ISSUE TITLE
Atualizar a tela de criação de missão com mais dois campos: tipo de medalha e medalha prereq

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/besouro-app#3]
@luizapeixe com o detalhamento da mecânica de gamificação, a tela de criação de missão vai precisar incluir mais dois parâmetros (cc @parrahenri ):
(i) campo para escolher o tipo de medalha que o usuário ganha ao concluir e
(ii) campo de pré-requisito onde o criador escolhe uma medalha como pré-requisito

**Comment by ricardopoppi** [comment]
@luizapeixe chegou a ver essa?

**Comment by luizapeixe** [comment]
eis a tela alterada: https://invis.io/Q2LUNUJFDPY#/302750828_Criar_Missa-o

pros dois campos, Tipo de medalha e Pré-requesito, deixei um campo com dropdown, começando com a opção "nenhum" por default, imaginando q uma missão pode não oferecer recompensa. Está correto?

**Comment by ricardopoppi** [comment]
Sim @luizapeixe melhor assim mesmo, pois deixa mais flexivel pro admin criar uma missão sem recompensa se for o caso.
