### ISSUE TITLE
Implementar o parágrafo inicial na home de missões previsto no wireframe

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/besouro-app#30]
Com base no wireframe existente: https://projects.invisionapp.com/d/main#/console/14558908/302750832/preview

Com o texto:

BOAS VINDAS!

Que legal que você quer mobilizar o Brasil contra a corrupção!

Aqui você encontra diferentes missões de mobilização e pode se tornar ativista nessa campanha!

(ver regras)

**Comment by parrahenri** [comment]
@luizapeixe, reformulando o texto:

BOAS VINDAS!

Que legal que você quer mobilizar o Brasil contra a corrupção!

Aqui você encontra diferentes missões de mobilização e pode se tornar ativista para conseguirmos unir o máximo possível de pessoas e eleger candidatos e candidatas comprometidos com o fim da corrupção!

(ver regras)

**Comment by luizapeixe** [comment]
ai vai a tela com o texto atualizado: https://invis.io/HWMC0W4D2JG#/302750832_Home_Feed

**Comment by parrahenri** [comment]
boa! acho que tá massa! lembrando que cliente vai validar e/ou ajustar na quinta
