### ISSUE TITLE
Botão "fechar" faltando nos modais

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/besouro-app#39]
Todos os modais implementados e futuros devem possuir o botão "fechar" como [nesse exemplo](https://projects.invisionapp.com/d/main#/console/14558908/305653432/preview#project_console), por conta de UX.

Atualmente os modais de "missão aceita" e "concluir missão" não possuem esse botão

**Comment by davidCarlos** [comment]
Farei isso, lembrando que o usuário pode fechar a modal apertando fora dela.

**Comment by ricardopoppi** [comment]
@davidCarlos essa issue estava como homolog, mas notei que nenhum modal/splash implementou o botão fechar conforme proposta dos wireframes: https://projects.invisionapp.com/d/main#/console/14558908/306925983/preview

**Comment by ricardopoppi** [comment]
@davidCarlos realmente, todos os modais devem ter o botão fechar, inclusive o modal de usuários deslogados, esse aqui: https://projects.invisionapp.com/d/main#/console/14558908/306943819/preview

mas, como conversamos, esse "X" no alto está confundindo. Pedi para trocar pelo asset de cadeado, copio a @luizapeixe pra indicar o melhor asset pra essa substituição

**Comment by luizapeixe** [comment]
@ricardopoppi ok! troquei o ícone de "X" pelo ícone de cadeado, [olha](https://projects.invisionapp.com/d/main#/console/14558908/306943819/preview). E já joguei o asset lá na [nossa pasta](https://drive.google.com/open?id=10FwPnDwN41xe_bDZ9woWzHXvlLUDg1cG) no drive
