### ISSUE TITLE
Criar proposta de card de missão "apagado" quando a missão expira o prazo

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/besouro-app#4]
Quando a missão expira o prazo, precisamos mostrar isso para o usuário no próprio card de missão. Uma ideia seria mostrar ele apagado com o aviso de expirado, mas de forma que permaneçam visíveis os indicadores que a missão gerou

**Comment by luizapeixe** [comment]
ok! segue uma primeira proposta: https://invis.io/D4LUUD28C9A#/305371736_Mobile_Portrait_Missa-o_Expirada

**Comment by ricardopoppi** [comment]
Legal, temos a interna de missão expirada. @luizapeixe falta agora uma proposta de como aparece o card de uma missão expirada na timeline (como regra de negócio, vai aparecer apenas na seção "minhas missões" para quem aceitou a missão e ela expirou antes do usuário concluir)

**Comment by luizapeixe** [comment]
Que tal assim? Um filtro da cor institucional #312783 sobrepõe a imagem com 85% de opacidade e o ícone e mensagem da missão expirada sobrepõe o filtro e a foto:

![captura de tela 2018-07-02 as 17 11 01](https://user-images.githubusercontent.com/6249788/42185463-5ff13ce0-7e1f-11e8-830b-b6f21b3971b6.png)

**Comment by ricardopoppi** [comment]
Por mim vamos por ai! (cc @parrahenri ). @luizapeixe pode criar tela no invision pra gente poder passar pra dev

**Comment by luizapeixe** [comment]
Ok! o card está exemplificado aqui na tela de "[minhas missões](https://invis.io/KYMC4N035H9#/302750833_Home_suas_Missoes)" e o [ícone do relógio tocando](https://drive.google.com/drive/folders/1_-5zo9m7dRiGfLML5ZInQOgJnqomBaIV?ogsrc=32) já está na pasta do drive

**Comment by ricardopoppi** [comment]
Maravilha. Issue #37 criada passando pra dev
