### ISSUE TITLE
Página inicial de missões para usuário deslogado tem problemas de UX

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/besouro-app#42]
Hoje, quando um usuário deslogado acessa o app:

1) Entra no feed de missões públicas
Aí ele tem as seguintes possibilidades de ação:
(i) Clicar na setinha de uma interna de missão
(ii) Clicar no hamburger e clicar no "fazer login" (que aliás está bem apagado)

Se ele vai pelo caminho (i) fica preso na interna sem ter o que fazer
Se ele vai pelo caminho (ii) ok, porque ao logar/registrar ele volta pra home de missões com os botões aparecendo.

Porém acho fundamental que os botões apareçam todos para o usuário deslogado, tanto o "aceitar missão" do card e da interna de missão, quanto a possibilidade de comentar. Essas duas ações disparam um gatilho para a tela de login/registro. Talvez até o clique no ítem de perfil dispare esse mesmo gatilho.

O que acha @luizapeixe ?

**Comment by luizapeixe** [comment]
Realmente o link para "login" está bem apagado. Poderíamos aplicar a cor roxa #312783 com 100% de opacidade para dar um pouco mais de destaque, mas o ideal seria aumentar o corpo de texto dele, ou ainda deixa-lo com um valor parecido ou igual ao "VISITANTE" , talvez o VISITANTE em branco e o FAZER LOGIN logo abaixo do VISITANTE, com mesmo valor porém com a cor roxa.

Agora, sobre o user deslogado ficar preso sem ação ao entrar na missão, penso que poderíamos criar mais uma tela de splash para aparecer qnd um user deslogado clicar em "aceitar missão", ou seja, invés dele ser direcionado automaticamente para a tela de login, um splash tipo assim:

https://invis.io/T8MIXHJKJ3W#/306943819_Mobile_Portrait_Splash_User_Deslogade

**Comment by ricardopoppi** [comment]
Boa @luizapeixe ! Vou criar uma issue só pra esse splash. Pode ser que fique pros aprimoramentos. De qq forma o @davidCarlos vai usar esse splash pro minhas missões conforme vc sugeriu lá no telegram
