### ISSUE TITLE
Erro de compartilhamento por whatsapp no android

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/besouro-app#43]
Ao compartilhar no whatsapp, android não dispara o app mas uma nova janela do browser. Veja imagem:

![photo_2018-07-03_00-29-53](https://user-images.githubusercontent.com/1162183/42197320-9a730d38-7e58-11e8-81cc-58da5fb6cf1a.jpg)

**Comment by davidCarlos** [comment]
O componente de compartilhamento só vai acessar a api nativa do celular, se o app estiver rodando com https. A modal só deve abrir quando o usuário acessa via browser, e nesse caso não há problemas. Ao acessar pelo celular, o componente tbm vai abrir via modal (devido a falta de https), e ai isso acarreta no bug descrito por essa issue.

**Comment by davidCarlos** [comment]
Com a configuração do https no ambiente, esse bug foi resolvido.
