### ISSUE TITLE
Implementar card de missão bloqueada quando o troféu pre-requisito não tiver sido obtido pelo usuário

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/besouro-app#45]
Atualmente temos um caso de uma missão que está associada a um troféu que só é desbloqueado com o recebimento de um troféu pré-requisito:

(iii) Troféu conferido pela missão mas que tem pre-requisito de outro troféu (bloqueado enquanto o usuário não ganhar o troféu super ativista):
Troféu Mobilizador (após completar a missão "Criar grupo de Whatsapp para mobilizar pela campanha"). PREREQ: Para o usuário ter acesso a essa missão, requer possuir "Troféu Super Ativista"

Na issue [ej-server#23](https://github.com/unidoscontraacorrupcao/ej-server/issues/23) a sugestão foi de que a imagem do troféu no perfil do usuário aparecesse com algum simbolo de "bloqueado". Como a missão também fica bloqueada até o usuário conseguir o troféu, precisamos de um card de missão que reflita essa condição, de preferencia com o mesmo símbolo escolhido na issue mencionada acima para manter coerencia de ux.

**Comment by luizapeixe** [comment]
que tal assim o card?

![captura de tela 2018-07-04 as 13 54 39](https://user-images.githubusercontent.com/6249788/42288624-dd3e5b7e-7f91-11e8-9bd5-ec4252c21bc4.png)

daí qnd o user clicar em "entenda" o mesmo splash apresentado na [issue #23](https://github.com/unidoscontraacorrupcao/ej-server/issues/23) pode abrir: https://invis.io/E4MIP6BDFP9#/306925983_Mobile_Portrait_Splash_Trofeu_Bloqueado

**Comment by parrahenri** [comment]
Senti falta de aparecer pelo menos o nome da missão. Assim ajuda a dar um gostinho e deixar a pessoa curiosa e afim de fazê-la!

**Comment by luizapeixe** [comment]
nessa tela na verdade aparece o nome da missão, ali abaixo da autoria. Só no quadro de troféus q não estava aparecendo, porém alterei o layout agora pouco incluindo o nome da missão no tb no quadro de medalhas: https://invis.io/DWMIRBF46QJ#/303032454_Perfil_2
