### ISSUE TITLE
Verificar carregamento de fontes em iphone

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/besouro-app#50]
- fontes FOLIO e HELVÉTICA não carregam no Iphone
- fonte helvética light não carregou em um dos desktops do pessoal

**Comment by ricardopoppi** [comment]
@luizapeixe @parrahenri preciso da ajuda de vcs pra reproduzir esse bug em outro iphone. Não há nada que impeça essa carga, então achamos que pode ter sido apenas uma demora na carga do CSS. Conseguem testar em algum iphone?

**Comment by parrahenri** [comment]
@luizapeixe esse bug foi mostrado pra vc né? foi o henrique que relatou ali na hora? minha sugestão é pedir pra ele reproduzir (se tiver sido ele msm)

**Comment by luizapeixe** [comment]
@parrahenri isso mesmo, pro Henrique não aparecia a Folio e para o rapaz sentado atrás de mim (não me lembro o nome dele) não carregou nem a Folio nem a Helvética Light no desktop. Falha minha não ter anotado qual navegador eles estavam usando :(

**Comment by parrahenri** [comment]
@luizapeixe se quiser perguntar pra ele: Henrique Bronzoni <hqbronzoni@gmail.com>
