### ISSUE TITLE
O clique no título, descrição e parte superior da img de capa no card de missão deveria levar para a interna

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/besouro-app#52]
o user é levado a pagina interna da missão clicando no ">" mas também deveria ser levado ao clicar no título, descrição e na parte superior da imagem de destaque da missão.

**Comment by davidCarlos** [comment]
Em conversa com o @ricardopoppi, decidimos deixar apenas o header do card clicavel (redirecionando para a interna de missão).
