### ISSUE TITLE
Ajustes de hierarquia e usabilidade dos botões no card e interna de missões

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/besouro-app#54]
Nesse momento só temos fôlego pra ajustes de posicionamento e alterações mínimas de estilo. Dentro dessas limitações creio que essa issue deve abordar:
(1) Qual o comportamento dos dois botões no card de missão (ex: só aparece o botão "aceitar", enquanto que o botão "concluir" passa a ser exclusivamente interno etc)
(2) Eventuais ajustes no card (dentro de limitações de fôlego)
(3) Eventuais ajustes na interna (dentro das mesmas limitações de fôlego

**Comment by parrahenri** [comment]
@luizapeixe quero te ouvir, mas a partir da experiência de uso lá dos participante da oficina temos de reformular. Veja o que notei:

1. botão ACEITAR logo no card (como já é hoje)
2. card com botão VER MISSÃO (esse daqui gerou muitos bugs, mas muita gente também se questionou se ele é necessário. Pq não mostra diretamente a missão?)
3. Card passa a mostrar o CONCLUIR MISSÃO (isso tb ficou prejudicado por causa do bug do ver missão, mas em linhas gerais todo mundo sentiu falta de que depois da missão ser apresentada haja algum botão que leve para a missão quando for algo digital).


Poderia ser:

1. ACEITAR
2. Mostrar direto da missão OU VER MISSAO funcionar
2.1 Nessa tela ter algo bem chamativo que diga : Vá lá fazer a missão e depois volta aqui pra nos avisar que concluiu
3. "Esconder" um pouco o botão concluir ou ao menos pensar um jeito que não gere uma ideia de que vc já vai clicar direto, reforçando essa orientação de "vá lá fazer e depois volta aqui" - talvez deixar só no card e não mostrar dentro da tela em que a missão é detalhada

**Comment by parrahenri** [comment]
@luizapeixe talvez tenha ficado confuso, mas o que pensei foi:

HJ:
card
splash
pagina da missão com o concluir em destaque

Sugestão:
1. card
2. pagina da missão com botão concluir indicando a narrativa (faça missão e depois volte pra concluir)

**Comment by luizapeixe** [comment]
Que tal assim, pessoal?

### - Na interna da missão:

O botão que antes era "CONCLUIR MISSAO" agora se mostra como uma versão _pressionada_ do botão ACEITAR MISSAO da página [interna da missão](https://invis.io/E7MSQD2V9Y5#/302750831_Missa-o_1) (lembrando que o user pode aceitar a missão tb a partir da interna da missão), e o recurso de CONCLUIR MISSÃO fica agora em segundo plano, próximo ao botão, junto com a frase de instrução de MISSAO ACEITA e destacando-se apenas pelo estilo do <a> do hyperlink. O que acham? Acha que essas alterações cabem no nosso fôlego, @ricardopoppi ?

ps.: também incluí a info de autoria da missão na interna.

![captura de tela 2018-07-09 as 11 18 21](https://user-images.githubusercontent.com/6249788/42455891-da76869c-8369-11e8-8096-3660e6c5a243.png)

### - nos cards:

Creio que podemos manter o card de missão a ser aceita [do mesmo jeito](https://invis.io/JQMSWEFH32F#/302750832_Home_Feed), com o botão sobreposto do jeito que está. Daí o card de missão aceita, inspirado nas soluções propostas pros cards de missão expirada e missão bloqueada (ver os últimos cards [dessa página](https://invis.io/XZMSXMMY8NP#/302750833_Home_suas_Missoes)), podemos fazer algo assim:

![captura de tela 2018-07-09 as 12 15 06](https://user-images.githubusercontent.com/6249788/42459278-c4091976-8371-11e8-8cb6-6f365dc08684.png)

o botão sobreposto deixa de existir e um filtro de #E6007E com 50% de opacidade sobrepõe a foto toda, com o título "MISSAO ACEITA" em #fff centralizado. E todo o card leva pra dentro da interna da missão. Nessa ideia o recurso de CONCLUIR MISSAO só existe dentro da interna da missão.

**Comment by ricardopoppi** [comment]
Olha, acho que temos uma boa proposta! Me parece que se manteve dentro do pedido de "ajustes sem reestruturações". Peço ao @davidCarlos opinar sobre isso.

Uma sugestão sobre a proposta: E se a gente replicasse no card uma mesma lógica de subtexto sobre a conclusão? Ex: "Já realizou a missão? Entre aqui para concluir" - que tal? (cc @parrahenri )

**Comment by parrahenri** [comment]
Gostei da proposta da @luizapeixe  e de sua complementação @ricardopoppi! vamos assim!

**Comment by ricardopoppi** [comment]
Então @luizapeixe atualiza esse ultimo detalhe no card de missão aceita e atualiza a interna pra refletir a nova dinâmica de conclusão. Me sinaliza qdo tiver atualizado que eu transformo essa issue em issue de implementação

**Comment by luizapeixe** [comment]
ok!

cards: https://invis.io/C5MTFFDEGM9#/302750833_Home_suas_Missoes
interna da missão aceita: https://invis.io/C2MTFHTRWQ5#/302750830_Missa-o_2
interna da missão concluída:  https://invis.io/AUMTFPQW6RN#/302750829_Missa-o_3
