### ISSUE TITLE
Privilegiar o comentário texto no splash de comprovação de missão

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/besouro-app#56]
Atualmente o print é privilegiado. O ideal é que um comentário do usuário seja suficiente para comprovação, e a opção de enviar arquivos esteja desprivilegiada e seja opcional

**Comment by luizapeixe** [comment]
alterado! https://invis.io/NYMSHTU3FCB#/302946971_Missa-o_Comprovac-a-o

**Comment by ricardopoppi** [comment]
Massa! @luizapeixe, um feedback: acha válido alguma indicação que o envio de arquivo é opcional? Fiquei pensando que seria melhor reforçar, devido aos feedbacks na oficina sobre isso

**Comment by luizapeixe** [comment]
sim @ricardopoppi ! acho que podemos deixar isso claro no texto, algo como: 

Agora é hora de pedir para o comitê de missões validar sua missão e oferecer sua recompensa, caso tenha. Para isso basta enviar a comprovação solicitada na missão descrevendo sua solução ou, _caso necessário_, fazendo o upload de imagens e/ou arquivos.

**Comment by ricardopoppi** [comment]
Acho que é isso! Já criei a issue #60 pra implementação dessa atualização, assim que possível @luizapeixe atualiza o wireframe com esse ajuste no texto mantendo o mesmo nome pra refletir no link que vou usar na issue

**Comment by luizapeixe** [comment]
ok! atualizado!
