### ISSUE TITLE
Criar proposta visual para denuncia de comentários na trédi na interna das missões

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/besouro-app#57]
temos que ter uma proposta visual de como encaixar o botão "denunciar" sem ele ser algo que carrega o visual dos comentários

**Comment by luizapeixe** [comment]
Que tal algo assim:

1. padrão
![captura de tela 2018-07-09 as 14 35 51](https://user-images.githubusercontent.com/6249788/42466489-77191044-8385-11e8-83e7-a2863907e11f.png)

2. no hover
![captura de tela 2018-07-09 as 14 36 55](https://user-images.githubusercontent.com/6249788/42466534-8fc6ac50-8385-11e8-8016-70d97e5b5407.png)

3. no clique
![captura de tela 2018-07-09 as 14 37 20](https://user-images.githubusercontent.com/6249788/42466559-a03d070a-8385-11e8-8ef6-c5429455ec86.png)
Daí invés desse NAO e SIM poderíamos aplicar algumas opções de motivo da denuncia, por exemplo: Comentário ofensivo; Comentário racista ou preconceituoso; Comentário incita discurso de ódio...

**Comment by ricardopoppi** [comment]
Gostei. Peço ao @davidCarlos opinar sobre complexidade (cc @parrahenri )

**Comment by parrahenri** [comment]
boa!

**Comment by ricardopoppi** [comment]
Conversei com @davidCarlos e @danielhmarinho como essa funcionalidade requer infra de moderação, ela ficará para o inicio da fase 2

**Comment by ricardopoppi** [comment]
Fechando essa, pois já criei a issue correspondente de implementação, milestone ETAPA 2
