### ISSUE TITLE
Problema na edição de perfil

### ISSUE THREAD

**Issue by danielhmarinho** [unidoscontraacorrupcao/besouro-app#62]
@ricardopoppi Debuggando a parte de edição de perfil entendi qual seria o problema. O código verifica o id do usuário para mandar o PUT na api, só que esse id tem ficado diferente do que está sendo salvo no banco. Isso ocorre pela criação de usuários pelo Django Admin. Quando se cria um usuário pelo admin não existe profile para ele, então o numero de profiles e o numero de usuários fica inconsistente, fazendo com que a requisição na API vá para o profile errado. Isso pode gerar problemas como edição de perfis de outros usuários sem querer além de quebrar caso o id não exista. Conversando com @davidCarlos vimos que a melhor solução para o momento, já que existem muitas issues no backlog para serem resolvidas, seria toda vez que um admin for criado no django um profile for criado para o mesmo. Adicionamos o campo de user no django admin na criação de profile para lembrar dessa inconsistência e associar um profile ao seu usuário explicitamente.

**Comment by ricardopoppi** [comment]
@danielhmarinho @davidCarlos estou de acordo com a solução proposta. Duas dúvidas:
1) os admins atuais foram amarrados com profiles ou ainda estão inconsistentes?
2) se a gente não criar admins pelo django e só apenas promover usuários criados pelo app esse problema não acontecerá, certo?

**Comment by danielhmarinho** [comment]
@ricardopoppi Sobre o primeiro item temos que olhar o banco de homologação pra ver se existem inconsistências, pois se algum admin foi criado apenas no django e depois não se cadastrou no app então problemas vão acontecer.

Sobre o segundo item você está correto. Se os usuários forem gerados apenas pelo app esse problema nunca vai ocorrer.

**Comment by danielhmarinho** [comment]
@ricardopoppi acabei de conferir aqui no que está no homologa e não tem problema de consistência. Enquanto no priorizamos essa correção basta deixar avisado que qualquer admin criado pelo django deve ser ciado um profile junto na mesma hora.

**Comment by ricardopoppi** [comment]
Perfeito. Como só eu estou com essa chave do admin, não teremos problema enquanto a correção não entrar. Pois se eventualmente eu precisar criar algum outro, farei apenas pelo app. Deixamos essa issue aberta @danielhmarinho, vc fecha ela qdo a correção for aplicada
