### ISSUE TITLE
Ao aprovar o receipt de missão no admin, está dando erro de "dois troféus"

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/besouro-app#69]
Django retorna com erro: get() returned more than one UserTrophy -- it returned 2!

![captura de tela de 2018-07-11 20-49-27](https://user-images.githubusercontent.com/1162183/42605061-485899e6-854c-11e8-9c84-d6eaaec8c47f.png)

**Comment by davidCarlos** [comment]
resolvida
