### ISSUE TITLE
Missões não carregam no chrome pra mac

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/besouro-app#7]
![whatsapp image 2018-06-27 at 03 30 10](https://user-images.githubusercontent.com/1162183/41981610-b38e9484-79ff-11e8-9e92-cbeacefc8fd3.jpeg)

**Comment by davidCarlos** [comment]
provavelmente foi um problema de disponibilidade da API, e não um bug do front. Fechando a issue por enquanto.
