### ISSUE TITLE
Caçar bug aleatório de botões sem evento. Normalmente acontece com os botões exibidos em modais

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/besouro-app#73]
Não parece haver uma regra específica para esse bug, a não ser que ele acontece com os botões exibidos em modais

**Comment by ricardopoppi** [comment]
@davidCarlos num dos momentos em que o bug aconteceu (no splash de aceite de missão, botão "ver missão"), detectei esses erros pelo inspector:

MyView1 failed to load TypeError: Failed to fetch https://dev.besouro.ejplatform.org/src/pages/inbox-page.js
    at HTMLScriptElement.f.onerror (profile:1)
app-shell.js:9400 MyView1 failed to load TypeError: Failed to fetch https://dev.besouro.ejplatform.org/src/pages/profile-page.js
    at HTMLScriptElement.f.onerror (profile:1)
profile:1 GET https://dev.besouro.ejplatform.org/src/pages/show-mission-page.js 404 (Not Found)
b @ profile:1
d @ profile:1
(anonymous) @ profile:1
Promise @ app-shell.js:9400
_pageChanged @ app-shell.js:9400
runObserverEffect @ app-shell.js:1
runEffectsForProperty @ app-shell.js:1
runEffects @ app-shell.js:1
_propertiesChanged @ app-shell.js:1
_flushProperties @ app-shell.js:1
_flushProperties @ app-shell.js:1
_invalidateProperties @ app-shell.js:1
_setProperty @ app-shell.js:1
Object.defineProperty.set @ app-shell.js:1
_routePageChanged @ app-shell.js:9400
runMethodEffect @ app-shell.js:1
runEffectsForProperty @ app-shell.js:1
runEffects @ app-shell.js:1
_propertiesChanged @ app-shell.js:1
_flushProperties @ app-shell.js:1
_flushProperties @ app-shell.js:1
_invalidateProperties @ app-shell.js:1
runNotifyEffects @ app-shell.js:1
_propertiesChanged @ app-shell.js:1
_flushProperties @ app-shell.js:1
_flushProperties @ app-shell.js:1
_invalidateProperties @ app-shell.js:1
setProperties @ app-shell.js:1
__tryToMatch @ app-shell.js:796
runMethodEffect @ app-shell.js:1
runEffectsForProperty @ app-shell.js:1
runEffects @ app-shell.js:1
_propertiesChanged @ app-shell.js:1
_flushProperties @ app-shell.js:1
_flushProperties @ app-shell.js:1
__enableOrFlushClients @ app-shell.js:1
_flushClients @ app-shell.js:1
_propertiesChanged @ app-shell.js:1
_flushProperties @ app-shell.js:1
_flushProperties @ app-shell.js:1
_invalidateProperties @ app-shell.js:1
runNotifyEffects @ app-shell.js:1
_propertiesChanged @ app-shell.js:1
_flushProperties @ app-shell.js:1
_flushProperties @ app-shell.js:1
_invalidateProperties @ app-shell.js:1
set @ app-shell.js:1
_triggerTrophyAction @ app-shell.js:7891
handler @ app-shell.js:1
_methodHost._addEventListenerToNode.e @ app-shell.js:1
_fire @ app-shell.js:1
forward @ app-shell.js:1
touchend @ app-shell.js:1
_handleNative @ app-shell.js:1
app-shell.js:9400 MyView1 failed to load TypeError: Failed to fetch https://dev.besouro.ejplatform.org/src/pages/show-mission-page.js
    at HTMLScriptElement.f.onerror (profile:1)

**Comment by ricardopoppi** [comment]
@davidCarlos fiz novos testes: todas as tentativas de clicar no botão "ver missão" estava em evento/ação

**Comment by davidCarlos** [comment]
Vou investigar com calma, tentei reproduzir até o momento não consegui. Olhando o log que vc mandou não tem nenhum erro relacionado a exibição da modal / falha no disparo do evento.

**Comment by ricardopoppi** [comment]
Acho que era o botão da interna mesmo, que decidimos pelo comportamento de fechar. Testei agora é o botão de ver troféus no splash de trofeu funcionou blz. 

@davidCarlos pode fechar essa qdo implementar o comportamento de fechar no "ver missão" na interna
