### ISSUE TITLE
Criar tag ilustrada do besouro

### ISSUE THREAD

**Issue by luizapeixe** [unidoscontraacorrupcao/besouro-app#77]
para substituir o "bug gigante" :

![photo_2018-07-18_22-54-39](https://user-images.githubusercontent.com/6249788/42916860-9a32852e-8add-11e8-837d-58fe26ea1d91.jpg)

**Comment by luizapeixe** [comment]
alguns experimentos:

a.
![captura de tela 2018-07-18 as 22 50 11](https://user-images.githubusercontent.com/6249788/42916895-c9978eae-8add-11e8-89b8-d9bf509c0ad7.png)

b. 
![captura de tela 2018-07-18 as 22 49 47](https://user-images.githubusercontent.com/6249788/42916937-d16bb66e-8add-11e8-9714-36839b360919.png)

**Comment by ricardopoppi** [comment]
sensacional @luizapeixe valeu demais!
